import type { Config } from "tailwindcss";
export default <Partial<Config>>{
  darkMode: "selector",
  theme: {
    fontFamily: {
      vivo: [
        "vivoTypeRegular",
        "ui-sans-serif",
        "system-ui",
        "sans-serif",
        "Apple Color Emoji",
        "Segoe UI Emoji",
        "Segoe UI Symbol",
        "Noto Color Emoji",
      ],
      montserrat: ["Montserrat", "Helvetica", "sans-serif"],
    },
    extend: {
      aspectRatio: {
        auto: "auto",
        square: "1 / 1",
        video: "16 / 9",
      },
      height: {
        sidebar: "var(--side-bar-width)",
        hideSidebar: "var(--hide-side-bar-width)",
        header: "var(--header-bar-height)",
        footer: "var(--footer-bar-height)",
        music: "var(--music-bar-height)",
        main: "var(--pt-main)",
      },
      minWidth: {
        header: "var(--header-bar-height)",
        sidebar: "var(--side-bar-width)",
        hideSidebar: "var(--hide-side-bar-width)",
        toolbar: "var(--tool-bar-width)",
        centered: "var(--centered-width)",
        music: "var(--music-bar-width)",
      },
      width: {
        header: "var(--header-bar-height)",
        sidebar: "var(--side-bar-width)",
        hideSidebar: "var(--hide-side-bar-width)",
        toolbar: "var(--tool-bar-width)",
        centered: "var(--centered-width)",
        music: "var(--music-bar-width)",
      },
      inset: {
        sidebar: "var(--side-bar-width)",
        hideSidebar: "var(--hide-side-bar-width)",
        toolbar: "var(--tool-bar-width)",
        header: "var(--header-bar-height)",
        music: "var(--music-bar-top)",
        main: "var(--pt-main)",
      },
      padding: {
        sidebar: "var(--side-bar-width)",
        hideSidebar: "var(--hide-side-bar-width)",
        toolbar: "var(--tool-bar-width)",
        header: "var(--header-bar-height)",
        main: "var(--pt-main)",
        footer: "var(--footer-bar-height)",
      },
      margin: {
        sidebar: "var(--side-bar-width)",
        hideSidebar: "var(--hide-side-bar-width)",
        header: "var(--header-bar-height)",
        toolbar: "var(--tool-bar-width)",
        footer: "var(--footer-bar-height)",
      },
      borderRadius: {
        none: "0",
        "3xs": "var(--border-radius-3xs)",
        "2xs": "var(--border-radius-2xs)",
        xs: "var(--border-radius-xs)",
        sm: "var(--border-radius-sm)",
        DEFAULT: "var(--border-radius-base)",
        md: "var(--border-radius-md)",
        lg: "var(--border-radius-lg)",
        xl: "var(--border-radius-xl)",
        "2xl": "var(--border-radius-2xl)",
        "3xl": "var(--border-radius-3xl)",
        full: "var(--border-radius-full)",
      },
      colors: {
        transparent: "transparent",
        current: "currentColor",
        theme: {
          50: "var(--theme-color-50)",
          100: "var(--theme-color-100)",
          200: "var(--theme-color-200)",
          300: "var(--theme-color-300)",
          400: "var(--theme-color-400)",
          500: "var(--theme-color-500)",
          600: "var(--theme-color-600)",
          700: "var(--theme-color-700)",
          800: "var(--theme-color-800)",
          900: "var(--theme-color-900)",
          950: "var(--theme-color-950)",
        },
        text: {
          1: "var(--text-1)",
          2: "var(--text-2)",
          3: "var(--text-3)",
          4: "var(--text-4)",
          5: "var(--text-5)",
        },
        headBar: "var(--bg-head-bar)",
        background: "var(--bg-background)",
        borderColor: "var(--border-color)",
        mask: "var(--bg-mask)",
        level: {
          b1: "var(--bg-level-b1)",
          1: "var(--bg-level-1)",
          2: "var(--bg-level-2)",
          3: "var(--bg-level-3)",
          4: "var(--bg-level-4)",
          5: "var(--bg-level-5)",
        },
      },
      screens: {
        xs: "600px",
        sm: "900px",
        md: "1200px",
        lg: "1500px",
        xl: "1800px",
      },
    },
  },
  plugins: [],
};
